using WePilot.Agent.Agents;
using WePilot.Agent.Infrastructure.Ai;
using WePilot.Agent.Infrastructure.Streaming;
using WePilot.Agent.Options;
using WePilot.Agent.Tools;
using WePilot.Agent.Tools.Results;
var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddEnvironmentVariables();
builder.WebHost.UseUrls(builder.Configuration["ASPNETCORE_URLS"] ?? "http://127.0.0.1:18441");
builder.Services.Configure<SemanticKernelOptions>(builder.Configuration.GetSection("SemanticKernel"));
builder.Services.Configure<AgentOptions>(builder.Configuration.GetSection("Agent"));
builder.Services.AddControllers();
builder.Services.AddScoped<KernelFactory>();
builder.Services.AddScoped<ChatAgentService>();
builder.Services.AddScoped<SseWriter>();
builder.Services.AddScoped<ToolExecutionContext>();
builder.Services.AddScoped<SampleTools>();
builder.Services.AddScoped<ProductionTools>();
builder.Services.AddScoped<ApsAnalysisTools>();
builder.Services.AddScoped<BusinessOrderDispatch>();
builder.Services.AddScoped<BusinessMaterialReadiness>();
builder.Services.AddSingleton<BusinessOrderSchedule>();
builder.Services.AddHttpClient("model", client => client.Timeout = Timeout.InfiniteTimeSpan);
var app = builder.Build();
app.MapControllers();
app.Run();
